### ISSUE TITLE
Standalone Docker auth secret 

### ISSUE THREAD

**Issue by rusenask** [synpse-hq/synpse#36]
If only secret is supplied like this

```yaml
spec:
  containers:
    - name: xx
      image: xx
      auth:       
        fromSecret: dockerhubCredentials
```

Try to base64 decode it into username/password. This would make auth a bit less cumbersome
