### ISSUE TITLE
Inline config files

### ISSUE THREAD

**Issue by rusenask** [synpse-hq/synpse#37]
We need a way to define some config files that might not be secrets at all. Now I use secrets even for things like caddy config but if we have something direct like this, it would be a nicer shortcut:

```yaml
name: my-app
scheduling:
  type: AllDevices
  selectors: {}
spec:
  containers:
    - name: my-app
      image: my-organization/app:1.0.1
      configFiles:
        - filepath: /path/to/config.conf
          contents: |
            <my config file contents>
            <more contents>
```
